services:
  scraper:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app            # In case you want to edit scripts on the host
      - ./:/web                # So update_index.py can overwrite index.html
    # No command runs by default — you can run on demand or schedule it.
    # Or if you want it to run right away, you can set "command: python /app/update_index.py"

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./:/usr/share/nginx/html:ro
    ports:
      - "1000:80"

